# Generated by Django 3.1 on 2020-11-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.ImageField(max_length=20, null=True, upload_to='')),
            ],
        ),
    ]
