# Generated by Django 3.0.8 on 2020-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFile',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='unnamed_file', max_length=64),
        ),
    ]
